import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers"
import Navbar from "@/components/layout/navbar"
import Container from "@/components/layout/container"
import { LoadingBar } from '@/components/loading-bar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <LoadingBar />
          <Navbar />
          {children}
          <div className="border-t border-gray-700">
            <Container className="flex items-center h-full justify-between pt-4">
              &copy; 2023 Hatofit
            </Container>
          </div>
        </Providers>
      </body>
    </html>
  )
}
