// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ppdGAL6ELv_MLrsIGLbozSd--MYplVU',
    appId: '1:499735113450:android:8b000161acffcf87c07193',
    messagingSenderId: '499735113450',
    projectId: 'zenta-hatofit0000',
    storageBucket: 'zenta-hatofit0000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-dc3mFcorLGp1-c7nnZUp58pI0-PFi4',
    appId: '1:499735113450:ios:0ef2066b7d952eefc07193',
    messagingSenderId: '499735113450',
    projectId: 'zenta-hatofit0000',
    storageBucket: 'zenta-hatofit0000.appspot.com',
    androidClientId: '499735113450-28k3fm9769lb16o9qtfolt4l62k06tv4.apps.googleusercontent.com',
    iosClientId: '499735113450-b7nof01d6mpvhvcpfmin5123726v2n4e.apps.googleusercontent.com',
    iosBundleId: 'edu.unesa.hatofit',
  );
}
